package cnuphys.bCNU.magneticfield.swim;

import java.awt.BasicStroke;
import java.awt.Color;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Point;
import java.awt.Polygon;
import java.awt.RenderingHints;
import java.awt.Stroke;
import java.awt.geom.Point2D;
import java.util.ArrayList;
import java.util.List;

import cnuphys.bCNU.drawable.DrawableAdapter;
import cnuphys.bCNU.graphics.GraphicsUtilities;
import cnuphys.bCNU.graphics.SymbolDraw;
import cnuphys.bCNU.graphics.container.IContainer;
import cnuphys.bCNU.graphics.style.LineStyle;
import cnuphys.lund.LundId;
import cnuphys.lund.LundStyle;
import cnuphys.splot.plot.X11Colors;
import cnuphys.swim.IProjector;
import cnuphys.swim.SwimMenu;
import cnuphys.swim.SwimTrajectory;
import cnuphys.swim.SwimTrajectory2D;
import cnuphys.swim.Swimming;

/**
 * An abstract class for dwaing trajectories from thje swimmer
 *
 * @author heddle
 *
 */
public abstract class ASwimTrajectoryDrawer extends DrawableAdapter implements IProjector {
	
	// used by XY plots to indicate for the z effect
	protected boolean zEffect;  //whether it is on or off
	protected double zView; // z view point for z effect
	protected double delZ; // max distance from the z view point for z effect 
	protected int maxLineWidth = 3;
	
	private double _maxPathLength = 1500; //whatever units the trajectory

	// colors
	protected static final Color sectChangeColor = X11Colors.getX11Color("purple", 128);
	protected static final BasicStroke planeStroke = GraphicsUtilities.getStroke(1.5f, LineStyle.SOLID);

	private static RenderingHints renderHints = new RenderingHints(RenderingHints.KEY_ANTIALIASING,
			RenderingHints.VALUE_ANTIALIAS_ON);
	static {
		renderHints.put(RenderingHints.KEY_RENDERING, RenderingHints.VALUE_RENDER_QUALITY);
	}

	// these are the 2D trajectories
	protected ArrayList<SwimTrajectory2D> _trajectories2D = new ArrayList<>(20);

	protected SwimTrajectory2D _closestTrajectory;

	protected double _minMarkR = 25; // cm

	
	/**
	 * Actual drawing method
	 *
	 * @param g         the graphics context
	 * @param container the base container
	 */
	@Override
	public void draw(Graphics g, IContainer container) {
		// draw any trajectories generated by swimming. These are not in
		// the event

		_trajectories2D.clear();
		_closestTrajectory = null;

		// Draw Monte Carlo Tracks?
		if (SwimMenu.getInstance().showMonteCarloTracks()) {
			List<SwimTrajectory> trajectories = Swimming.getMCTrajectories();

			if (trajectories != null) {

				for (SwimTrajectory trajectory : trajectories) {
					// give a chance to veto a trajectory, e.g. no chance it
					// will appear on this view (for example)
					if (!veto(trajectory)) {
						_trajectories2D.add(projectedTrajectory(trajectory));
					}
				}
			}
		}

		// Draw Reconstructed Tracks?
		if (SwimMenu.getInstance().showReconstructedTracks()) {
			List<SwimTrajectory> trajectories = Swimming.getReconTrajectories();

			if (trajectories != null) {

				for (SwimTrajectory trajectory : trajectories) {

					// give a chance to veto a trajectory, e.g. no chance it
					// will
					// appear on this view (for example)
					if (!veto(trajectory)) {
						_trajectories2D.add(projectedTrajectory(trajectory));
					}
				}
			}
		}

		//aux tracks
		if (true) {
			List<SwimTrajectory> trajectories = Swimming.getAuxTrajectories();

			if (trajectories != null) {

				for (SwimTrajectory trajectory : trajectories) {
					if (!veto(trajectory)) {
						_trajectories2D.add(projectedTrajectory(trajectory));
					}
				}
			}
		}

		drawTrajectories(g, container);
	}

	private SwimTrajectory2D projectedTrajectory(SwimTrajectory trajectory) {
		double scale = coordinateScale(trajectory);
		return new SwimTrajectory2D(trajectory, (point, projected) -> {
			double[] normalized = point;
			if (scale != 1.0) {
				normalized = point.clone();
				normalized[0] *= scale;
				normalized[1] *= scale;
				normalized[2] *= scale;
			}
			project(normalized, projected);
		});
	}

	private static double coordinateScale(SwimTrajectory trajectory) {
		return "cnuphys.CLAS12Swim.CLAS12Trajectory".equals(trajectory.getClass().getName()) ? 1.0 : 100.0;
	}

	protected void drawTrajectories(Graphics g, IContainer container) {
		for (SwimTrajectory2D trajectory2D : _trajectories2D) {
			drawSwimTrajectory(g, container, trajectory2D);
		}
	}
	
	/**
	 * The the z view. Only relevant if zEffect is true.
	 * @param zView the new value
	 */
	public void setZView(double zView) {
		this.zView = zView;
	}

	/**
	 * Set the maximum path length for a trajectory. If a trajectory is longer than
	 * this, it will be truncated.
	 * 
	 * @param maxPathLength the maximum path length in whatever units the trajectory
	 */
	public void setMaxPathLength(double maxPathLength) {
		_maxPathLength = maxPathLength;
	}
	
	/**
	 * Here we have a chance to veto a trajectory. For example, we may decide that
	 * the trajectory won't appear on this view (assuming a view owns this drawer)
	 * and so don't bother to compute it. The default implementation vetoes nothing.
	 *
	 * @param trajectory the trajectory to test.
	 * @return <code>true</code> if this trajectory is vetoed.
	 */
	protected boolean veto(SwimTrajectory trajectory) {
		return false;
	}

	// denote sector changes
	protected void markSectorChanges(Graphics g, IContainer container, SwimTrajectory2D trajectory) {

		int[] indices = trajectory.sectChangeIndices();
		if (indices == null) {
			return;
		}

		SwimTrajectory traj3D = trajectory.getTrajectory3D();
		Point pp = new Point();
		for (int idx : indices) {

			double r = coordinateScale(traj3D) * traj3D.getR(idx);
			if (r > _minMarkR) {
				Point2D.Double wp = trajectory.getPath()[idx];
				container.worldToLocal(pp, wp);
				SymbolDraw.drawDiamond(g, pp.x, pp.y, 5, Color.cyan, sectChangeColor);
			}
		}
	}

	/**
	 * Draw a trajectory
	 *
	 * @param g          the graphics object
	 * @param container  the rendering container
	 * @param trajectory the 2D (already projected) trajectory to draw
	 */
	protected void drawSwimTrajectory(Graphics g, IContainer container, SwimTrajectory2D trajectory) {

		if (!acceptSimpleTrack(trajectory)) {
			return;
		}

		LundId lid = trajectory.getTrajectory3D().getLundId();

		String source = trajectory.getSource().toLowerCase();

		if (source.contains("hitbasedtrkg::hbtracks")) {
			draw2DTrajectory(g, container, trajectory, Color.yellow);
			return;
		} else if (source.contains("timebasedtrkg::tbtracks")) {
			draw2DTrajectory(g, container, trajectory, X11Colors.getX11Color("dark orange"));
			return;
		} else if (source.contains("cvtrec::tracks")) {
			draw2DTrajectory(g, container, trajectory, X11Colors.getX11Color("green"));
			return;
		} else if (source.contains("cvt::tracks")) {
			draw2DTrajectory(g, container, trajectory, X11Colors.getX11Color("coral"));
			return;
		} else if (source.contains("hitbasedtrkg::aitracks")) {
			draw2DTrajectory(g, container, trajectory, X11Colors.getX11Color("spring green"));
			return;
		} else if (source.contains("timebasedtrkg::aitracks")) {
			draw2DTrajectory(g, container, trajectory, X11Colors.getX11Color("magenta"));
			return;
		}
		else {
			Graphics2D g2 = (Graphics2D) g;
	
			Stroke oldStroke = g2.getStroke();
			LundStyle style = LundStyle.getStyle(lid);
			g.setColor(style.getLineColor());
			g2.setStroke(style.getStroke());
			draw2DTrajectory(g, container, trajectory, style.getLineColor());
		
			g2.setStroke(oldStroke);
		}
	}

	public abstract boolean acceptSimpleTrack(SwimTrajectory2D trajectory);
	
	private void draw2DTrajectory(Graphics g, IContainer container, SwimTrajectory2D trajectory, Color color) {
		if (zEffect) {
			zEffectDrawSwimTrajectory(g, container, trajectory, color);
		} else {
			plainDrawSwimTrajectory(g, container, trajectory, color);
		}
	}

	/**
	 * Draw a trajectory
	 *
	 * @param g          the graphics object
	 * @param container  the rendering container
	 * @param trajectory the 2D (already projected) trajectory to draw
	 */
	private void plainDrawSwimTrajectory(Graphics g, IContainer container, SwimTrajectory2D trajectory, Color color) {

		Graphics2D g2 = (Graphics2D) g;
		g2.setRenderingHints(renderHints);

		Polygon poly = new Polygon();
		Point2D.Double path[] = trajectory.getPath();

		if (path == null) {
			return;
		}

		Point pp = new Point();
		Point2D.Double oldWP = null;
		
		//running pathlength in cm
		double pathLength = 0;

		for (Point2D.Double wp : path) {
			if (oldWP != null) {
				pathLength += wp.distance(oldWP);
			} 
			oldWP = wp;
			if (pathLength > _maxPathLength) {
				break;
			}

			container.worldToLocal(pp, wp);
			poly.addPoint(pp.x, pp.y);
			
		}

		if (poly.npoints > 1) {
			g2.setColor(color);
			g2.setStroke(planeStroke);
			g.drawPolyline(poly.xpoints, poly.ypoints, poly.npoints);
		}
	}

	
	/**
	 * Draw a trajectory
	 *
	 * @param g          the graphics object
	 * @param container  the rendering container
	 * @param trajectory the 2D (already projected) trajectory to draw
	 */
	private void zEffectDrawSwimTrajectory(Graphics g, IContainer container, SwimTrajectory2D trajectory, Color color) {
 
		double zValues[] = zValues(trajectory.getTrajectory3D());
		if (zValues == null) {
			plainDrawSwimTrajectory(g, container, trajectory, color);
			return; // no z effect
		}
		
		Point2D.Double path[] = trajectory.getPath();

		if (path == null) {
			return;
		}
		
		if (path.length != zValues.length) {
			System.err.println("SwimTrajectoryDrawer: path and zValues lengths do not match");
			plainDrawSwimTrajectory(g, container, trajectory, color);
			return;
		}
		
		//draw with z effect. The trajectory is drawn in segments of varying line width
		// and alpha. The line varies from maxLineWidth to 1 pixel width based on how 
		// far (in an absolute sense) the z value is from the zView point. It should
		// drop from maxLineWidth to 1 pixel width at delZ distance from the zView point,
		// then stay at 1 pixel width for larger distances. The color of the segment
		//should be the provided color with an alpha that varies from 255 to 64 up to
		// delZ, then drops to 32 for larger distances.This is to give a 3D effect for the line.

		
		Graphics2D g2 = (Graphics2D) g;
		g2.setRenderingHints(renderHints);

		BasicStroke oldStroke = (BasicStroke) g2.getStroke();
		Point pp1 = new Point();
		Point pp2 = new Point();


		Point2D.Double oldWP = null;
		double pathLength = 0;

		for (int i = 1; i < path.length; i++) {
			oldWP = path[i - 1];
			Point2D.Double wp = path[i];
			
			double dz1 = Math.abs(zValues[i - 1] - zView);
			double dz2 = Math.abs(zValues[i] - zView);
			
			pathLength += oldWP.distance(wp);
			if (pathLength > _maxPathLength) {
				break;
			}

			// interpolate attributes for the segment
			double avgDZ = 0.5 * (dz1 + dz2);

			// line width calculation
			float lineWidth = (float) (avgDZ < delZ
					? 1 + (maxLineWidth - 1) * (1 - avgDZ / delZ)
					: 1);

			// alpha calculation
			int alpha;
			if (avgDZ < delZ) {
				double frac = avgDZ / delZ;
				alpha = (int) (255 - frac * (255 - 96));
			} else {
				lineWidth = 1f; // minimum line width
				alpha = 64;
			}
			alpha = Math.max(0, Math.min(255, alpha)); // clamp

			Color segColor = new Color(color.getRed(), color.getGreen(), color.getBlue(), alpha);
			g2.setColor(segColor);
			BasicStroke stroke = GraphicsUtilities.copyWithNewWidth(oldStroke, lineWidth);
			g2.setStroke(stroke);

			container.worldToLocal(pp1, oldWP);
			container.worldToLocal(pp2, wp);
			g2.drawLine(pp1.x, pp1.y, pp2.x, pp2.y);
		}

		g2.setStroke(oldStroke);

	}

	private static double[] zValues(SwimTrajectory trajectory) {
		if (trajectory == null || trajectory.isEmpty()) {
			return null;
		}

		double scale = coordinateScale(trajectory);
		double[] zValues = new double[trajectory.size()];
		int index = 0;
		for (double[] point : trajectory) {
			zValues[index++] = scale * point[2];
		}
		return zValues;
	}
		
	
	/**
	 * Get the distance of closest approach to any 2D (projected) trajectory.
	 *
	 * @param wp the point in question
	 * @return the closest distance. The closest trajectory will be cached in
	 *         <code>closestTrajectory</code>.
	 */
	public double closestApproach(Point2D.Double wp) {
		_closestTrajectory = null;

		double minDist = Double.POSITIVE_INFINITY;
		if ((_trajectories2D == null) || (_trajectories2D.size() < 1)) {
			return minDist;
		}

		// loop over all trajectories that are drawn
		for (SwimTrajectory2D trajectory2D : _trajectories2D) {
			double dist = trajectory2D.closestDistance(wp);

			if (dist < minDist) {
				_closestTrajectory = trajectory2D;
				minDist = dist;
			}
		}

		return minDist;
	}

	/**
	 * @return the closestTrajectory
	 */
	public SwimTrajectory2D getClosestTrajectory() {
		return _closestTrajectory;
	}

}
